// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeixGN7AJCqo3z1uBm5Ms2JarWkNpX61g',
    appId: '1:872188609739:web:1a63938a3e2ec3ee02474e',
    messagingSenderId: '872188609739',
    projectId: 'random-cocktail-app',
    authDomain: 'random-cocktail-app.firebaseapp.com',
    storageBucket: 'random-cocktail-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACzk-K_BNstD0jc74AJR_XNKe0R_8pqjI',
    appId: '1:872188609739:android:56b8eb824948ed0a02474e',
    messagingSenderId: '872188609739',
    projectId: 'random-cocktail-app',
    storageBucket: 'random-cocktail-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZhJ2dQfuva_JLvKRwBivxFv-zMsIu9FY',
    appId: '1:872188609739:ios:cf7b21907692c5f802474e',
    messagingSenderId: '872188609739',
    projectId: 'random-cocktail-app',
    storageBucket: 'random-cocktail-app.appspot.com',
    androidClientId: '872188609739-6ko5pdp4i9aic7bktauvbjr1jf341ds4.apps.googleusercontent.com',
    iosClientId: '872188609739-up458ds58e9qmk1qjq01i1gc3l3cp9ns.apps.googleusercontent.com',
    iosBundleId: 'com.example.randomCocktailApp',
  );
}
